# Site settings
title: Travis McArthur
email: tdmcarthur@wisc.edu 
description: |
  Travis McArthur <br />
  Ph.D. Candidate <br />
  Department of Agricultural & Applied Economics <br />
  University of Wisconsin-Madison

## baseurl: "" # the subpath of your site, e.g. /blog/
## url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  tdmcarthur

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# url: http://tdmcarthur.github.io
url: http://www.travismcarthur.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/travismcarthur"
## baseurl: ""

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Ph.D. Candidate"
excerpt_separator: "<!--more-->"

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: true
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

# description: > # this means to ignore newlines until "baseurl:"